In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding='latin1')

In [3]:
data

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [4]:
unique_items = data['Item'].unique()

In [5]:
print("Unique items in the dataset:", unique_items)

Unique items in the dataset: ['Population' 'Grand Total' 'Vegetal Products' 'Animal Products'
 'Cereals - Excluding Beer' 'Wheat and products' 'Rice and products'
 'Barley and products' 'Maize and products' 'Rye and products' 'Oats'
 'Millet and products' 'Sorghum and products' 'Cereals, Other'
 'Starchy Roots' 'Cassava and products' 'Potatoes and products'
 'Sweet potatoes' 'Yams' 'Roots, Other' 'Sugar Crops' 'Sugar cane'
 'Sugar beet' 'Sugar & Sweeteners' 'Sugar (Raw Equivalent)'
 'Sweeteners, Other' 'Honey' 'Pulses' 'Beans' 'Peas'
 'Pulses, Other and products' 'Treenuts' 'Nuts and products' 'Oilcrops'
 'Soyabeans' 'Groundnuts (Shelled Eq)' 'Sunflower seed'
 'Rape and Mustardseed' 'Cottonseed' 'Coconuts - Incl Copra' 'Sesame seed'
 'Olives (including preserved)' 'Oilcrops, Other' 'Vegetable Oils'
 'Soyabean Oil' 'Groundnut Oil' 'Sunflowerseed Oil' 'Rape and Mustard Oil'
 'Cottonseed Oil' 'Palmkernel Oil' 'Palm Oil' 'Coconut Oil'
 'Sesameseed Oil' 'Olive Oil' 'Maize Germ Oil' 'Oilcrops Oil, Other'
 'Vegetables' 'Tomatoes and products' 'Onions' 'Vegetables, Other'
 'Fruits - Excluding Wine' 'Oranges, Mandarines'
 'Lemons, Limes and products' 'Grapefruit and products' 'Citrus, Other'
 'Bananas' 'Plantains' 'Apples and products' 'Pineapples and products'
 'Dates' 'Grapes and products (excl wine)' 'Fruits, Other' 'Stimulants'
 'Coffee and products' 'Cocoa Beans and products' 'Tea (including mate)'
 'Spices' 'Pepper' 'Pimento' 'Cloves' 'Spices, Other'
 'Alcoholic Beverages' 'Wine' 'Beer' 'Beverages, Fermented'
 'Beverages, Alcoholic' 'Alcohol, Non-Food' 'Meat' 'Bovine Meat'
 'Mutton & Goat Meat' 'Pigmeat' 'Poultry Meat' 'Meat, Other' 'Offals'
 'Offals, Edible' 'Animal fats' 'Butter, Ghee' 'Cream'
 'Fats, Animals, Raw' 'Fish, Body Oil' 'Fish, Liver Oil' 'Eggs'
 'Milk - Excluding Butter' 'Fish, Seafood' 'Freshwater Fish'
 'Demersal Fish' 'Pelagic Fish' 'Marine Fish, Other' 'Crustaceans'
 'Cephalopods' 'Molluscs, Other' 'Aquatic Products, Other'
 'Aquatic Animals, Others' 'Aquatic Plants' 'Miscellaneous' 'Infant food'
 'Sugar non-centrifugal' 'Palm kernels' 'Ricebran Oil']

In [6]:
selected_item = 'Wine'

In [7]:
grouped_data = data.groupby('Item').sum()

In [8]:
if selected_item in grouped_data.index:
    # Retrieve the sum for the selected item for the years 2015 and 2018
    production_2015_sum = grouped_data.loc[selected_item, 'Y2015']
    production_2018_sum = grouped_data.loc[selected_item, 'Y2018']

In [10]:
print(f"Total {selected_item} produced in 2015:", production_2015_sum)
print(f"Total {selected_item} produced in 2018:", production_2018_sum)

Total Wine produced in 2015: 4251.81
Total Wine produced in 2018: 4039.32

In [11]:
S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [12]:
# Calculate correlation between 'Element Code' and each year
correlation_with_element_code = {}
for column in data.columns:
    if column.startswith('Y'):
        correlation = data['Element Code'].corr(data[column])
        correlation_with_element_code[column] = correlation

# Find the year with the minimum correlation
least_correlated_year = min(correlation_with_element_code, key=correlation_with_element_code.get)
min_correlation = correlation_with_element_code[least_correlated_year]

print(f"The year with the least correlation with 'Element Code' is {least_correlated_year} with a correlation coefficient of {min_correlation}.")

The year with the least correlation with 'Element Code' is Y2016 with a correlation coefficient of 0.023443997584961424.

In [15]:
len(data['Area'].unique())

49

In [17]:
data.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [19]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment